/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://tybebkidedofqavukggj.supabase.co";
export const projectId = supabaseUrl.replace("https://", "").replace(".supabase.co", "");
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5YmVia2lkZWRvZnFhdnVrZ2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwOTI5NjEsImV4cCI6MjA4OTY2ODk2MX0.L-ZuwKzEcyZgYMjh6ePrp7pB1jjTkzDhEIo1UyYBSlo";
export const functionName = "server";
export const functionBaseUrl = `${supabaseUrl}/functions/v1/${functionName}`;
